### PR TITLE
[WIP] Handle python versioning syntax

### PR DESCRIPTION
**Pull request by davegaeddert**
@paulortman I'm not sure what we want to do here. The test explains it but basically a python library using `1.1.0.devN` gets coerced into `1.1.0+devN` as build metadata, and then build metadata is matched by the filter. What I would have expected to happen for now is for those `.dev` versions to simply be skipped as invalid semver (not a positive integer for patch)...

https://github.com/rbarrois/python-semanticversion/blob/master/semantic_version/base.py#L114
https://www.python.org/dev/peps/pep-0440/

I think we started using their `coerce` to fill out the zeros? Do we want to do that ourselves and then not coerce? Or does their `partial` work for us somehow here? Other thoughts?

### CODE REVIEW

**Comment by paulortman** [comment]
@davegaeddert Okay, so I've got a simple, perhaps incorrect, fix to this issue.  I'm simply rejecting all version strings that have a "build" component once parsed.  It successfully passes your test, but I'm not totally confident it solves whole problem.  Thoughts?

**Comment by paulortman** [comment]
PS) I don't understand why tox tests aren't working...

**Comment by davegaeddert** [comment]
@paulortman would it be dumb to do a two-step semver parsing thing there? So first try without coercing (so valid semver could go through, builds included), and if it is not proper semver then we can try coerce? And if the coerce comes back with build, then we throw it away?

I don't have an example at the moment but I have a feeling we may end up wanting/needing to support the build field like we do everything else...

**Comment by davegaeddert** [comment]
@paulortman and I'm not sure on the Travis tests...looks like it's just `pypy` that's failing, which I know very little about. Their versioning scheme is a little weird at a glance but it looks like the build says it is using Python 2.7.8[pypy-2.5.0-final] and pypy-2.5.0 seems pretty old in their releases... I'm good to remove pypy if you are but that may be a cop out. I can't remember what the issue was but the python 2.6 builds also used to fail, so I just removed that assuming we don't care to go back that far.

FWIW the cookiecutter thing we used for this has since changed to using [tox-travis](https://pypi.python.org/pypi/tox-travis), which seems to be a way more intuitive setup to me. They also removed the pypy version.

**Pull request merged**
